### ISSUE TITLE
Should we rename rustler_codegen?

### ISSUE THREAD

**Issue by scrogson** [rusterlium/rustler#119]
It seems that the new convention is to call crates `<root>_derive` should we do the same?

**Comment by jorendorff** [comment]
I like the new convention, but I don't know if this can be done without breaking existing code.  Seems like users will have to update their Cargo.toml files if the crate is renamed.

Or `rustler_codegen` could be maintained, as an identical copy of the new `rustler_derive` crate, just for backward compatibility.

**Comment by scrogson** [comment]
@jorendorff I'm thinking for a 1.0 release. We're going to be breaking the API slightly already in preparation for 1.0, so might as well break everything while we're at it :stuck_out_tongue_winking_eye:

**Comment by treyzania** [comment]
I don't think that people should be able to expect a high level of compatibility for a transition from `0.x` to `1.x`.  If there's going to be breaking changes then let's just rip the bandaid off and make as many as needs to be done.  Depending on your point of view, a `0.x` to `1.x` would be *even more breaking* than a `1.x` to `2.x` or anything above that.

**Comment by hansihe** [comment]
Seeing as we might start adding procedural macros to the codegen crate, I am not sure if doing a rename is fitting anymore.

**Comment by evnu** [comment]
@hansihe can you provide some more context?

**Comment by scrogson** [comment]
I will have a PR soon that should make this more clear...
