### ISSUE TITLE
Fix CI for real

### ISSUE THREAD

**Issue by scrogson** [rusterlium/rustler#121]
The recently merged CI fixes feel a bit hacky. It would be nice to use `rust` as the language and test against all rust channels.

We need a better way to install `erlang` and `elixir`. Is `kerl` and `kiex` available inside all Travis builds?

**Comment by scrogson** [comment]
Should we try GitHub Actions for this?

**Comment by filmor** [comment]
I have no experience with Github Actions, are they better than Travis regarding hackiness?

**Comment by scrogson** [comment]
I've recently set it up to try it out for https://github.com/scrogson/no-way-jose and I was surprised how simple it was to get everything working without any fuss.
