### ISSUE TITLE
Consider using the official Elixir autoformatter

### ISSUE THREAD

**Issue by walkr** [rusterlium/rustler#160]
**Suggestion:**

I think it would be nice to use the Elixir formatter as it will make contributions easier and standardized with respect to code layout.

**Comment by scrogson** [comment]
I'm personally not a big fan of the Elixir code formatter in its current state. It produces less readable code (IMHO). So I'm 👎 

I will leave it up to @hansihe

**Comment by walkr** [comment]
Fair enough. 

Have you expressed your gripes regarding the formatter to the Elixir team? Maybe we can make it better.

I know typically a formatter cannot satisfy everyone's taste, yet I believe it provides formatting consistency across codebases. In addition, one could ensure better code readability, by properly breaking down the code into small, readable, functional blocks.

**Comment by davydog187** [comment]
I added the formatter in #218 

I think enough time is passed where it has become a community standard, and it would be great for Rustler to adopt is as well.

**Comment by scrogson** [comment]
Fixed in #253
