### ISSUE TITLE
docs not available on docs.rs

### ISSUE THREAD

**Issue by NobbZ** [rusterlium/rustler#193]
The documentation of rustler 0.20.0 and 0.19.0 is not available on docs.rs:

> docs.rs failed to build rustler-0.20.0
> Please check build logs and if you believe this is docs.rs' fault, report into this issue report.

**Comment by hansihe** [comment]
https://github.com/rust-lang/docs.rs/issues/23#issuecomment-470207985

**Comment by hansihe** [comment]
This has been fixed.

https://docs.rs/rustler/0.20.0/rustler/
