### ISSUE TITLE
Add support for OTP 22

### ISSUE THREAD

**Issue by rsimmonsjr** [rusterlium/rustler#211]
Erlang OTP 22 is out and my system automatically updated with it when I updated all my packages. That promptly broke my ability to compile any code using rusler. Rustler simply issues a panic that its not supported and aborts.

**Comment by scrogson** [comment]
Yes. This usually happens with each major release. I will work on updating soon.

**Comment by myfreeweb** [comment]
Building with the environment variable `RUSTLER_NIF_VERSION=2.14` worked fine for me… maybe rustler should automatically use the latest supported version? Does BEAM ever break NIF backwards compatibility?

**Comment by evnu** [comment]
> Yes. This usually happens with each major release. I will work on updating soon.

Do you plan to implement the new API (`enif_compare_pids/2` and others), or will there be version bump to the new NIF version first?

**Comment by scrogson** [comment]
The next release will be our first release with a vendored `erl_nif_sys` crate. We will need to look through the additions in the latest NIF API and add support for those in that crate. Then add a safe API in Rustler.

**Comment by kraythen** [comment]
> The next release will be our first release with a vendored `erl_nif_sys` crate. We will need to look through the additions in the latest NIF API and add support for those in that crate. Then add a safe API in Rustler.

What do you mean by "vendored `erl_nif_sys` crate?

**Comment by scrogson** [comment]
@kraythen `erlang_nif-sys` is now going to be `erl_nif_sys` and it is part of the workspace in `rustler`.

We made the mistake of depending on `erlang_nif-sys` with `>= 0.6` so now we can’t publish a new version with fixes without breaking everyone’s builds.

**Comment by rsimmonsjr** [comment]
Ok I get the breaking builds issue but of you dont sometimes you will be stuck in legacy forever. It might be better to just increment to 1.0 and break them.
