### ISSUE TITLE
Make use of clippy?

### ISSUE THREAD

**Issue by evnu** [rusterlium/rustler#222]
I played around with `cargo clippy` and rustler the other day and wondered if there is interest to bring that upstream. I fixed the warnings from `cargo clippy --all-features --all-targets` in a [branch](https://github.com/evnu/rustler/tree/clippy). The suggestions mainly aimed at removing superfluous (as of Rust 2018) lifetime annotations, removing unnecessary captures and replacing references where move is more appropriate due to `Copy` being implemented for a type. But clippy found two things which might be of interest:

1. `bin.as_mut_slice().write(self.as_bytes()).expect("memory copy of string failed")` should use `write_all()` instead of `write`, as `write` does not guarantee to write all at once
2. `ptr.offset(offset as isize)` should be `ptr.add(offset)`, as `offset` can never be a negative number.

**Comment by scrogson** [comment]
Yeah, I've used it in the past. I probably should have run it with all the recent changes I did 🦀
