### ISSUE TITLE
macOS platform hack does not pick up workspace cargo configuration

### ISSUE THREAD

**Issue by evnu** [rusterlium/rustler#235]
The platform hack for [macOS](https://github.com/rusterlium/rustler/blob/master/rustler_mix/lib/mix/tasks/compile.rustler.ex#L98) does not consider a cargo configuration within a workspace, but only the configuration local to a crate. This results in unnecessary warnings when the correct arguments are already provided within the workspace-wide configuration.

**Comment by evnu** [comment]
@scrogson Any update here?

**Comment by scrogson** [comment]
I haven't spent any time thinking about this. Do we want to pull in a JSON library to remove a warning? I think the answer is no.

Given that you have more experience with this setup, what do you think?

**Comment by scrogson** [comment]
I guess we could just check the root first and then fallback to the crate_path: https://github.com/rusterlium/rustler/blob/master/rustler_mix/lib/mix/tasks/compile.rustler.ex#L120

**Comment by evnu** [comment]
I also don't think that we should use a json library just for this. To get the workspace root, we might don't need to parse json, a regex could suffice. I can give that a try.

**Comment by evnu** [comment]
See #381, we might need to parse the JSON produced by `cargo metadata` there. If so, maybe we can pick up this issue here again to find the proper configuration for a crate.
