### ISSUE TITLE
docs.rs broken

### ISSUE THREAD

**Issue by filmor** [rusterlium/rustler#236]
(I guess) since rustler_sys (erlang_nif-sys, erl_nif_sys) is now part of the normal rustler build process, the docs.rs build fails: https://docs.rs/crate/rustler/0.21.0/builds/183891

This means there is no nice way to check rustler's docs for the current version online.

**Comment by evnu** [comment]
Related to #193?

**Comment by filmor** [comment]
Possibly. Maybe one could just commit the generated code for the most recent supported version of OTP and fall back to that during build instead of requiring Erlang to be available?

**Comment by NobbZ** [comment]
Might become even worse:

https://blog.rust-lang.org/2019/09/18/upcoming-docsrs-changes.html

**Comment by evnu** [comment]
Note that you can always run `cargo doc` locally as a workaround. That puts a `doc/` directory into your target dir. There, you can find the documentation for all crates used in your project.

**Comment by NobbZ** [comment]
It is, as you said, a workaround. I can not link to a piece of documentation I've only available locally.
