### ISSUE TITLE
"could not find `atoms` in `rustler`" in fresh project, when using 0.21.0

### ISSUE THREAD

**Issue by JayPeet** [rusterlium/rustler#260]
Hello. 

In a fresh Elixir project, using rustler 0.21.0, I can't compile the auto generated lib.rs file due to "could not find `atoms` in `rustler`".

This is with
Windows
Elixir V 1.9.1
OTP 22
rustc 1.38.0

Have I missed some kind of setup step, or is this an issue?

**Comment by scrogson** [comment]
Hi @JayPeet, I believe you're referring to the `rustler::atoms!` macro in the README? This is currently not released but only on `master` it will be in the next release.

See #249 for more details.

**Comment by NobbZ** [comment]
You probably looked at `master`s `README`, instead of the one that belongs to your version. Some macros git renamed recently.

It's `rustler_atoms` in your version (or was it `rustler_atom`?).

**Comment by JayPeet** [comment]
I see

Thats strange, because I just used the 0.21.0 hex package, which generated that template file.

After changing the lib.rs file to be correct, I now get "protocol String.Chars not implemented for {:error, :bad_name} of type Tuple". I can investigate this further :)

**Comment by scrogson** [comment]
Oh! I think it might be missing the `rustler` prefix on that. In `0.21` it should be:

```rs
mod atoms {
    rustler::rustler_atoms! {
        atom ok;
    }
}
```

**Comment by scrogson** [comment]
> After changing the lib.rs file to be correct, I now get "protocol String.Chars not implemented for {:error, :bad_name} of type Tuple". I can investigate this further :)

Sounds like you might be calling `to_string/1` on the returned value in your Elixir code? Feel free to paste your code. Without that, I'm just guessing :smile:

**Comment by JayPeet** [comment]
Sorted it.

I has set the wrong otp_app atom in the "use Rustler" options :)

Closing this now, thank you all for the assistance.

**Comment by Tuxified** [comment]
+1 as I also ran into this issue today, luckily found it when looking for closed issues :P

**Comment by scrogson** [comment]
I've pinned this issue so hopefully others will see it quicker until we publish 0.22.
