### ISSUE TITLE
Yocto Bitbake support?

### ISSUE THREAD

**Issue by mischief901** [rusterlium/rustler#274]
I'm trying to get a library that uses Rustler to build in Bitbake, but I'm having some trouble. There are other Rust and Elixir libraries that build just fine, so this is not an infrastructure problem. However when I try and build the library that uses Rustler, there are issues with fetching and compiling the Rust dependencies.

Has anyone successfully got this to work? This might be more of a `meta-rust` issue.

**Comment by mischief901** [comment]
I spent a couple of hours on this, but got nowhere. I can hack away at it, but it seemed like the right time frame to ask if someone had success.

**Comment by scrogson** [comment]
@mischief901 I'm not familiar with what Bitbake or Yocto is. Can you provide some context? Do you have any links to the library you are trying to compile?

**Comment by mischief901** [comment]
yocto is a way to cross compile for various architectures, usually embedded systems. https://www.yoctoproject.org/

This was mostly just asking if someone had tried to do something along these lines before. The people involved with Rustler are much more responsive than yocto, so I figured it was worth a shot to ask here first. Feel free to close this if you think it is out of line.

The issue has to do with where `cargo` fetches the crates for building the Rust component of the library. The solution may be as simple as pointing it to the correct location so bitbake can find everything. I guess what I am looking for is the temporary build locations of files when a `mix release` is performed.

**Comment by evnu** [comment]
> The issue has to do with where cargo fetches the crates for building the Rust component of the library.

So this happens during the download of dependencies? A copy of the error message would be great :)

**Comment by scrogson** [comment]
Closing. Please re-open if you still have questions.

**Comment by joaohf** [comment]
Hello,

Just a note here: the pieces needed to support rustler on YP/OE (meta-erlang) has been implemented. https://github.com/meta-erlang/meta-erlang/issues/200
