### ISSUE TITLE
Improve ergonomics of binaries

### ISSUE THREAD

**Issue by szlend** [rusterlium/rustler#286]
I feel like working with binaries in Rustler is not as convenient as it could be. Additionally, you have to jump through hoops to build a binary without unnecessary copies.

There are two things that we could improve:
- Making `OwnedBinary` encodable. Optimally we would be able to return an `OwnedBinary` without having to manually `release` it.
- Implement common traits like `Write` and `Extend` for `OwnedBinary` so it can be used directly with functions that write bytes.

For the first part, the problem is that the `Encoder` trait takes a `&self`, so there is no way that we can `release` the binary to be encoded. I think the encoder taking a `&self` probably makes sense, though I see no reason why we couldn't also encode by taking ownership in a `rustler::nif` decorated function.

The second part should be relatively straightforward, though we'd have to think about how to efficiently grow the binary as it's being appended.

This is something I could possibly work on, though I'm still not very familiar with the code so maybe I'm missing something. I'd like to hear your thoughts on this first.

**Comment by filmor** [comment]
Part 1 is pretty simple: Just implement `NifReturnable` on `OwnedBInary` like it's done here: https://github.com/rusterlium/rustler/blob/master/rustler/src/codegen_runtime.rs

For the second part, there is `realloc_or_copy` on `OwnedBinary` that could be used for this, though I'm not convinced this is ever a good idea. If you know the size up-front you can just get a cursor to the underlying slice to write on, if you don't know the size you are probably better of with building an IO list (as in a `Vec<OwnedBinary>` to be converted to an Erlang list of `Binary`) and passing that directly back without writing it all into the same buffer.

Nice ergonomics for building an IO list would be a great addition :)

**Comment by szlend** [comment]
Great, I'll prepare a PR for the first part.

As for the second part, conceptually you would do the same thing in Rust when you don't know the size up-front. You would create a new `Vec`, maybe give it some hint capacity, write to it and let it reallocate when needed. So unless there's a greater cost to reallocating binaries in BEAM, I don't see why not. Though IO lists are probably a more BEAM friendly solution. We'd have to do some tests comparing the cost of Vec/Binary reallocation I guess.

**Comment by filmor** [comment]
`Vec` grows exponentially (not strictly speaking guaranteed, but they promise an amortised O(1) `push` and AFAIK they realise this right now via a constant growth factor), `realloc` doesn't. This means a simple `Write` implementation based on a simple `realloc` to the new size will have very unfavourable growth behaviour. This *could* be countered by implementing an exponential growth strategy in `OwnedBinary`, but I'm not convinced having that kind of code in there is really helpful.

In C++ one could probably just override the allocator for `std::vector`, I don't think such a thing exists in Rust right now.
