### ISSUE TITLE
Should Rust's unit be casted to nil or remain an empty tuple in NIF return values?

### ISSUE THREAD

**Issue by elbow-jason** [rusterlium/rustler#290]
This is more of a question than an issue, but I _think_ this is the right forum for discussion and sake of posterity.

Currently a NIF that returns a Rust unit `()` value (either explicitly or having no return value) results in an empty tuple in Elixir. 

The question is: Should we change Rustler to encode the Rust unit `()` as a `nil` in Elixir?

Example:
```rust
#[rustler::nif]
fn returns_a_unit() {
}
```

```elixir
iex(1)> SomeApp.Native.returns_a_unit()
{}
```

Thoughts?

**Comment by scrogson** [comment]
`()` in Rust is definitely not the same as an empty tuple...that would be `(,)` in Rust. So...yeah, I think we should probably do something different here....

**Comment by filmor** [comment]
Rust's unit is definitely the same as an empty tuple (last line of https://doc.rust-lang.org/reference/types/tuple.html), the current behaviour is correct.

**Comment by filmor** [comment]
We could try to forbid this particular case in the codegen, though, forcing users to at least spell out `-> ()`, as I also see the potential for confusion here.

I'd be against `nil` as an automatic conversion (in general) as this is an Elixirism without special meaning anywhere else in BEAM-land.

**Comment by OvermindDL1** [comment]
I'm also against auto conversion to `nil`, `nil` is an atom in elixir, and the nil type in the BEAM is the empty list which is ambiguous and an atom definitely doesn't seem proper.  The empty list would make sense, but the usual BEAM thing to return for functions that don't really return anything is often just `ok`, which is also an atom, which I'm not a fan of returning.  Something inline to the model like the empty tuple or empty list seems best to me.  Or disallowing it to force returning something that makes sense for the case.

**Comment by scrogson** [comment]
> Rust's unit is definitely the same as an empty tuple (last line of https://doc.rust-lang.org/reference/types/tuple.html), the current behaviour is correct.

I guess I stand corrected 😄

**Comment by elbow-jason** [comment]
Thank you all for the feedback and info; learned a lot. 

The clear winner for preference is to keep Rust's unit `()` as `{}` in Elixir/Erlang.
