### ISSUE TITLE
Decoding Maps of arbitrary length

### ISSUE THREAD

**Issue by hazardfn** [rusterlium/rustler#312]
**Rustler Version:** 0.22.0-rc.0

This is perhaps more a question of something I am doing wrong but it doesn't seem like `NifMap` supports maps of length N > 1. For example trying to decode the following map:

```elixir
%{
    1 => %SomeStruct{},
    2 => %SomeStruct{}
   }
```

Where `%SomeStruct{}` is appropriately set up in the Nif as `NifStruct` and can be decoded singularly and the map key is just a `u32`.

What's the correct type for a map of arbitrary length? The documentation also only supplies examples for a map with 1 KV pair.

To be clear I realise I can use MapIterator when it's passed in as part of a NIF function but I am talking about maps that are part of structs, for example:

```rust
#[derive(Clone, Debug, Eq, Hash, NifMap, PartialEq)]
pub struct Counts {
    id: String,
    count: u32,
}

#[derive(Clone, Debug, Eq, Hash, NifStruct, PartialEq)]
#[module = "SomeModule.SomeStruct"]
pub struct SomeStruct {
    pub r#type: i32,
    pub remaining: u32,

    /// An elixir map `%{Counts.id() => pos_integer()}`
    pub counts: Counts,
}
```

```elixir
%SomeStruct{type: 1, remaining: 0, counts: %{"hello" => 12, "world" => 25}}
```

If I try to make `pub counts` of type `MapIterator` I have to put lifetimes everywhere, I assume because it shares the lifetime of the `Env`

**Comment by evnu** [comment]
`NifStruct` and `NifMap` are proc-macros which that the Elixir map matches the Rust type. What you need to do here is to decode the incoming map into a variable-length type. This is not (yet) implemented for maps, but only for lists. What you could try is to introduce a newtype `struct Count(HashMap<String, u32>)` and use that in your `SomeStruct`. Then, implement `Encoder` and `Decoder` for that type by iterating over the map. It would be useful to have this in rustler directly I guess.

**Comment by hazardfn** [comment]
@evnu yeah implementing Enc/Dec for HashMap works fine as you say, I think it would be great out of the box functionality though 👍
