### ISSUE TITLE
Panic on rust 1.44.0

### ISSUE THREAD

**Issue by rjmac** [rusterlium/rustler#313]
The release of rust-lang/rust#66059 in 1.44.0 makes things panic that didn't before, and rustler is affected by it.  The changes in #239 fix it, and that cherry-picks (almost) cleanly on top of 0.21.0.  Perhaps it would be a good idea to release a version 0.21.1 with that change, if 0.22 isn't ready for release yet?

**Comment by Lakret** [comment]
For those also affected by this issue, the temporary fix is (for macOS):

```bash
rustup install 1.43.0
rustup default 1.43.0-x86_64-apple-darwin
```

For me the error looked like this:

```
thread '<unnamed>' panicked at 'attempted to leave type `rustler_sys::ErlNifResourceFlags` uninitialized, which is invalid', /Users/.../.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/mem/mod.rs:661:5
```

**Comment by filmor** [comment]
Just to be clear, this panics when compiling, not in the NIF, is that right? I think we can reasonably backport that patch and do an intermediary patch release.

**Comment by rjmac** [comment]
It panics during `mix compile`, but rustc is done and mix is doing something that's actually trying to load the library at that point.  It's a runtime check for undefined behavior that rustc is inserting.

**Comment by filmor** [comment]
@scrogson @hansihe I created a branch that backports the patch to 0.21 and bumps the version to 0.21.1 at https://github.com/rusterlium/rustler/tree/rustler-0.21-backport, you only need to check it out and run

    pushd rustler_mix
    mix hex.publish
    popd
    pushd rustler
    cargo publish
    popd
    pushd rustler_codegen
    cargo publish
    popd

I suggest you do that as soon as possible, this can result in some very nasty surprises for people in production.

**Comment by scrogson** [comment]
v0.21.1 published. @filmor thanks for taking care of the changes :+1:
