### ISSUE TITLE
Converting complex types from Rust to Elixir

### ISSUE THREAD

**Issue by GildedHonour** [rusterlium/rustler#321]
How are complex types, structs, slices, traits, etc..., converted from Rust to Elixir? 

How does this function have to be exported?

```

struct MyStruct1 {
  //........
}


struct MyStruct2 {
  //........
  var3: Struct3
}

struct Struct3 {
  //........
}

#[rustler::nif]
pub fn get_data1(a: i32, b: String, c: MyStruct1) -> MyStruct2 {
  //....
}
```

**Comment by evnu** [comment]
The `rustler_codegen` crate has proc-macros to generate Encoders/Decoders automatically. See [the testsuite](https://github.com/rusterlium/rustler/blob/master/rustler_tests/native/rustler_test/src/test_codegen.rs) for some examples.

**Comment by evnu** [comment]
Also, if you are using `rustler-0.22-rc.0`, you can refer to the [crate documentation](https://docs.rs/rustler/0.22.0-rc.0/rustler/), specifically the [derive](https://docs.rs/rustler/0.22.0-rc.0/rustler/#derives) section.

**Comment by evnu** [comment]
Closing, feel free to reopen if we need to extend the documentation for this.
