### ISSUE TITLE
Rustler Compiled Library is Missing

### ISSUE THREAD

**Issue by Mazyod** [rusterlium/rustler#326]
Hi, thanks for starting this great open source project!

## Brief

I am using rustler as a nested dependency, and since `v0.22.0rc`, which I am using via pulling `master` branch, I think the new compilation approach doesn't copy the files correctly when creating a release. It works when I try to run the same release command twice or more, though.

### Code

```elixir
defmodule DamaLogic.NifBridge do
  use Rustler, otp_app: :dama_logic, crate: "damalogic_damaprocess"

  [...]
end
```

Running `mix release` for the first time in a clean docker environment.

#### During compilation

```
226	
227	03:31:43.683 [warn]  The on_load function for module Elixir.DamaLogic.NifBridge returned:
228	{:error, {:load_failed, 'Failed to load NIF library: \'/work/_build/prod/lib/dama_logic/priv/native/libdamalogic_damaprocess.so: cannot open shared object file: No such file or directory\''}}
229	
230	Generated dama_logic app
231	
```

#### After compilation

Running `find . -iname '*.so'`

```
./deps/dama_logic/priv/native/libdamalogic_damaprocess.so

./_build/prod/rel/dama_server/lib/runtime_tools-1.14/priv/lib/trace_ip_drv.so
./_build/prod/rel/dama_server/lib/runtime_tools-1.14/priv/lib/dyntrace.so
./_build/prod/rel/dama_server/lib/runtime_tools-1.14/priv/lib/trace_file_drv.so
./_build/prod/rel/dama_server/lib/crypto-4.6.5/priv/lib/crypto.so
./_build/prod/rel/dama_server/lib/crypto-4.6.5/priv/lib/crypto_callback.so
./_build/prod/rel/dama_server/lib/crypto-4.6.5/priv/lib/otp_test_engine.so

./_build/prod/lib/dama_logic/native/damalogic_damaprocess/release/deps/libdamalogic_damaprocess.so
./_build/prod/lib/dama_logic/native/damalogic_damaprocess/release/deps/librustler_codegen-1426f88bc646ec0e.so
./_build/prod/lib/dama_logic/native/damalogic_damaprocess/release/libdamalogic_damaprocess.so
```

(Newlines added by me for clarity)

## Expectation

I would expect the output of the `*.so` to be within the `_build` directory instead of the `deps` directory given that `:build_embedded` is set to `true`. If the `priv` copying is happening before compilation, I guess this would cause the issue of breaking only during the first attempt of generating a release?

I will attempt to make a small repro repo once I get around to it.

Thanks,

**Comment by Mazyod** [comment]
Seems like this issue happens even with a simple project that pulls rustler directly.

Repro - see github actions, test fail, but they succeed locally if I run them twice:
https://github.com/Mazyod/rustler-demo

**Comment by Mazyod** [comment]
Another finding:

if `:build_embedded` is `false` **and** the `priv` directory exists, it would be symlinked and test succeed. However, for releases, `:build_embedded` is usually `true` for releases, so testing it as `true` for `MIX_ENV=test` also caused the issue, even with the `priv` directory initially present...

To summarize:
- If the developer has `priv` directory created, and `:build_embedded == false`, this issue will not appear.
- If the developer doesn't have `priv` directory, and `:build_embedded == false`, test would fail the first time, then succeed since `priv` would have been generated.
- If the developer has `:build_embedded == true`, test would fail the first time, then succeed since `priv` would have been generated.

**Comment by evnu** [comment]
Thanks for the report @Mazyod and the minimal example. I will try to find some time to look into it.

**Comment by evnu** [comment]
> If the priv copying is happening before compilation, I guess this would cause the issue of breaking only during the first attempt of generating a release?

I think that might be the cause here. We copy the resulting lib in [compiler.ex](https://github.com/rusterlium/rustler/blob/master/rustler_mix/lib/rustler/compiler.ex#L127) to `priv`. [`load_path`](https://github.com/rusterlium/rustler/blob/master/rustler_mix/lib/rustler.ex#L106) however indicates that the file should be placed into `_build/test/lib/rustler_dep/priv/`.

**Comment by Mazyod** [comment]
> > If the priv copying is happening before compilation, I guess this would cause the issue of breaking only during the first attempt of generating a release?
> 
> I think that might be the cause here. We copy the resulting lib in [compiler.ex](https://github.com/rusterlium/rustler/blob/master/rustler_mix/lib/rustler/compiler.ex#L127) to `priv`. [`load_path`](https://github.com/rusterlium/rustler/blob/master/rustler_mix/lib/rustler.ex#L106) however indicates that the file should be placed into `_build/test/lib/rustler_dep/priv/`.

Honestly, I tried before to copy files to _build directory directly, and it caused much headaches. (e.g. dependency of a dependency). Ensuring the library generates the built artifact to priv before Mix copies the priv contents seems like the safest bet. It worked when Rustler provided a custom compiler.

**Comment by Mazyod** [comment]
Just to add, if there is a safe and “proper” way to build artifacts directly to build_dir, that would be amazing actually. It needs to be tested with nested dependencies though.

**Comment by sezaru** [comment]
So, is there any solution for this bug? I'm using latest version (0.22.0-rc.1) because of OTP 24 for my library (https://hex.pm/packages/r_zstd/1.1.0-rc.2).

But when I add the library as a dependency for another project, it fails to find the nif when compiling and during runtime.

When compiling I get this error:
``` elixir
21:01:43.131 [warn]  The on_load function for module Elixir.RZstd.Native returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'/home/sezdocs/blibs/_build/dev/lib/r_zstd/priv/native/libr_zstd_nif.so: cannot open shared object file: No such file or directory\''}}
```

And when running a command from the library I get this error:
```elixir
iex(1)> RZstd.compress!("abc", 5)

21:01:56.765 [warn]  The on_load function for module Elixir.RZstd.Native returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'/home/sezdocs/blibs/_build/dev/lib/r_zstd/priv/native/libr_zstd_nif.so: cannot open shared object file: No such file or directory\''}}

** (UndefinedFunctionError) function RZstd.Native.compress/2 is undefined (module RZstd.Native is not available)
    (r_zstd 1.1.0-rc.2) RZstd.Native.compress("abc", 5)
    (r_zstd 1.1.0-rc.2) lib/r_zstd.ex:1: RZstd.compress!/2
```

You can easily reproduce this if you create any empty elixir project and add this to deps:
```elixir
  defp deps do
    [
      {:r_zstd, "~> 1.1.0-rc.2"},
    ]
  end
```

Is there any solution for that?

**Comment by Mazyod** [comment]
@sezaru you might want to try to create `priv` directory ahead of time in order to ensure it will be symbolically linked and the app will be able to detect the Rust library in the `_build` folder. (assuming `:build_embedded == false` )

**Comment by sezaru** [comment]
Thanks, @Mazyod it works if I change the library to build_embedded == false and create the priv directory. I will use this workaround for now and create a new version for my library.

But is there any more complex reason this was not fixed yet or is it just that there was no available time yet to tackle this?

**Comment by sezaru** [comment]
Also, testing with my library, I found out that it works if I only create the priv directory before building the project, regardless if `build_embeded` is `false` or `true`.

**Comment by sezaru** [comment]
Ok, I talked too soon...

It is kinda bizarre, but regardless if I add build_embedded == false or not, this only works if my library is added as a git dependency:
```elixir
{:r_zstd, git: "https://github.com/sezaru/r_zstd.git", tag: "v1.1.0-rc.4"}
```

If I change this line to using the hex published package of the same code, it doesn't work anymore:
```elixir
{:r_zstd, "~> 1.1.0-rc.4"},
```

**Comment by sezaru** [comment]
Ok, I figured it out, and now I have a definitive workaround for my library.

The above error was happening because if `hex.publish` sees that the directory you are trying to add is empty, it will ignore it (so my priv directory was not added), to fix that, I added a `README.md` file inside priv directory and then changed my package option in mix.env to:

```elixir
  defp package do
    [
      name: @app,
      maintainers: [@author],
      licenses: [@license],
      files: ~w(mix.exs lib README.md native/Cargo.* native/src priv/README.md),
      links: %{"Github" => @github}
    ]
  end
```

Note the `priv/README.md`.

Also, just doing this makes the library work without needing to change `build_embedded` to false.

**Comment by Mazyod** [comment]
Didn't realize you were uploading to Hex, great workaround. Personally, I'm just using the dependency through git.

**Comment by evnu** [comment]
I think I found the root cause of this (see #361): The `priv` directory is filled by `mix` before rustler puts the compiled libraries. We originally had a workaround for that (https://github.com/rusterlium/rustler/commit/d053522fe8b08bdacacb64592b22536e23ff3853), but forgot to add that to the refactored compiler.
