### ISSUE TITLE
Template generation issue

### ISSUE THREAD

**Issue by epinault** [rusterlium/rustler#354]
So first I noticed that 0.21.2 was never published on hex.pm  so I am using 0.21.1 

That. being said , it looks like master and that version have completely changed the default generated lib.rs see

https://github.com/rusterlium/rustler/commit/eba1d3d354c6b40d4e3206932be60510f982977f#diff-28fa2be52fc216393677208f7c29ed212f9274541dd1b1ebca42dd2089bdbb5c. 

That file generated in 0.21.1 does not compile at all with Rust because of the missing import for Atom at the top. Also Encoder seems problematic

Any change we can get 0.22 out with the new template?

**Comment by evnu** [comment]
> Any change we can get 0.22 out with the new template?

See #364.

**Comment by evnu** [comment]
We just released v0.22.0 which should contain working templates.
