### ISSUE TITLE
Odd difference between ErlNifTermType and TermType returned by `Term.get_type()`

### ISSUE THREAD

**Issue by Qqwy** [rusterlium/rustler#380]
[enif_get_type](http://erlang.org/doc/man/erl_nif.html#enif_term_type) returns an enum value depending on the type of value a particular term is.

Rustler currently uses [`Term.get_type()`](https://docs.rs/rustler/0.22.0/rustler/struct.Term.html#method.get_type), which returns a [TermType](https://docs.rs/rustler/0.22.0/rustler/enum.TermType.html).

There is a difference in the types returned by these two approaches.
Under the hood, `get_type` [is implemented as](https://docs.rs/rustler/0.22.0/src/rustler/dynamic.rs.html#21) a bunch of `is_*` checks.

However, there are two downsides with this approach:

1. They are slower;
2. They do not disambiguate between integers and floats.

`rustler_sys` [does seem to know about the ErlNifTermType](https://github.com/rusterlium/rustler/blob/4786f233a971058d0f677e0686bdf465dd458f01/rustler_sys/src/rustler_sys_api.rs#L308), but it doesn't seem to be used anywhere else in the code right now.

What would be the best way to improve this situation? I would be willing to contribute with a PR or two if someone can tell me which approach to take.

**Comment by evnu** [comment]
Note that `enif_get_type` is rather recent (OTP 22). Rustler currently supports OTP 20.3 as well (at least according to the github actions). To implement that in a backwards-compatible way, `Term.get_type()` could call into a feature-gated helper. For OTP >= 22, this would call into `enif_get_type` and `match` on the resulting enum, and for OTP < 22, the current logic would be used. See [`Term.map_from_arrays()`](https://github.com/rusterlium/rustler/blob/master/rustler/src/types/map.rs#L30) for an example on functions feature-gated to the NIF version.

The feature-gate mechanism uses `build.rs` to determine the NIF version. The version check can be overridden with `RUSTLER_NIF_VERSION` as well.

> They do not disambiguate between integers and floats.

As long as we need to maintain backwards compatibility, this would still be the case.

**Comment by evnu** [comment]
`TermType` and `ErlNifTermType` don't match exactly. For example, `TermType` has `Number`, while `ErlNifTermType` does not. Maybe we should have another function then to implement `enif_get_type`? It is unfortunate that `Term.get_type()` is already taken. So maybe we should not implement this for OTP < 22 at all, but instead disambiguate between the two?

**Comment by evnu** [comment]
See https://github.com/rusterlium/rustler/pull/538, which tackles this problem.

**Comment by filmor** [comment]
#538 has been merged and released, closing this.
