### ISSUE TITLE
Bad error handling in config

### ISSUE THREAD

**Issue by kristoff3r** [rusterlium/rustler#394]
I just spent a long time debugging a debian docker image which segfaulted when running `cargo metadata`. During this I encountered a counter-intuitive error path here: https://github.com/rusterlium/rustler/blob/fbedf17f8249fe6a1b23d69ff5e838388a89b27f/rustler_mix/lib/rustler/compiler/config.ex#L80-L89

`System.stop` is documented as having the spec `no_return()`, but it actually calls an underlying Erlang function that schedules a shutdown and returns `:ok`. This means the code continues running for a short while, which in my case was long enough to hit a type error inside `Jason.decode!`.

I don't know what the "correct" fix is, but printing an error and calling `System.halt` instead would have saved me a couple of hours.

**Comment by evnu** [comment]
I think the correct way to handle this would be to either match on `{metadata, 0}` or by raising an exception I think. Shutting down the whole VM looks wrong, I didn't think that through in #386. I won't be near a working development environment for some time, so maybe somebody of @rusterlium/core could take a look into this.
