### ISSUE TITLE
Awesome! Yay! Push new release to Hex for Mac M1 fix?

### ISSUE THREAD

**Issue by madasebrof** [rusterlium/rustler#406]
Hey! So amazing! Just had minor issue on Mac M1 that is fixed if I pull from git:

```elixir
  defp deps do
    [
      # {:rustler, "~> 0.22.2"}
      {:rustler, git: "https://github.com/rusterlium/rustler.git", sparse: "rustler_mix"}
    ]
  end
```
mix task `mix rustler.new` from `{:rustler, "~> 0.22.2"}` has the old `.cargo/config` file still there.

new `native/[NIF_NAME]/.cargo/config` (which fixes nif build errors on M1 Macs):

```rust
[target.'cfg(target_os = "macos")']
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]
```

Right now, the only warning I get when using the git `rustler_mix` is:

```sh
==> rustler
Compiling 7 files (.ex)
warning: variable "code" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/rustler/compiler/config.ex:85: Rustler.Compiler.Config.external_resources/2

Generated rustler app
```

**Comment by philss** [comment]
I think this one can be closed. Version [0.23.0](https://github.com/rusterlium/rustler/blob/master/CHANGELOG.md#0230---2021-12-22) was released with this fix.
