### ISSUE TITLE
Generalise derive macros to enums

### ISSUE THREAD

**Issue by turion** [rusterlium/rustler#426]
It would be great if all kinds of `enum`s could have a derive macro. I'd propose that `NifStruct` should be implemented for `enum`s as well, and there should be a new derive macro `NifAtomTuple` that would work coherently for structs and enums. (EDIT: `NifAtomTuple` should be identical to `NifRecord`.)

Some code examples that should work:

```rust
#[derive(NifStruct)]
enum Foo {
    #[module = "Foo"]
    Foo { foo1: i64, foo2: i64 },
    #[module = "Bar"]
    Bar { bar: bool },
}
```

```rust
/// Encodes to `{:foo, foo1, foo2}`
#[derive(NifAtomTuple)]
struct Foo {
    foo1: i64,
    foo2: i64,
}
```

So this is like an ad-hoc `NifRecord`, except that we don't need a bona-fide record on the Elixir side, and it also should work for enums:

```rust
#[derive(NifAtomTuple)]
enum Foo {
    /// Encodes to `{:foo, foo1, foo2}`
    Foo {
        foo1: i64,
        foo2: i64,
    },
    /// encodes to `{:bar, bool}`
    Bar(bool),
}
```

~In fact, the special case for a constructor without arguments coincides with `NifUnitEnum`. (In this light, `NifAtomTuple` could also be called `NifUnitEnum`, or we could deprecate `NifUnitEnum` for `NifAtomTuple` in the long run.)~

EDIT: I was wrong about `NifUnitEnum`.

**Comment by turion** [comment]
I'm willing to implement this if there is demand for it. (Leave a :+1: or comment in that case)

**Comment by turion** [comment]
I just realised that `NifAtomTuple` should generate the same code like `NifRecord`! After all, a record is a tuple where the first field is an atom serving as an identifying tag. So this issue really just boils down to generalising `NifStruct` and `NifRecord` to enums.

**Comment by turion** [comment]
> So this is like an ad-hoc NifRecord, except that we don't need a bona-fide record on the Elixir side, and it also should work for enums:

To decode & encode, we don't need the record on the Elixir side anyways. We'll receive a tuple, whereas the record definition on Elixir side is really just macros to work with the data in a convenient way.

**Comment by evnu** [comment]
@turion We have a more generalized macro with #440. I will close this ticket here, feel free to reopen if we missed some functionality with the generalized macro.
