### ISSUE TITLE
How to write to `/tmp/…` instead of `/usr/…` to fix build on Render.com

### ISSUE THREAD

**Issue by BurntCaramel** [rusterlium/rustler#449]
When I try using Rustler on the Render.com hosting service, my build always fails as it tries to write to `/usr/local/rustup/tmp/…`

```
Apr 18 05:56:26 PM  info: syncing channel updates for '1.60.0-x86_64-unknown-linux-gnu'
Apr 18 05:56:26 PM  error: could not create temp file /usr/local/rustup/tmp/5xaeur6g1t7vgi4z_file: Read-only file system (os error 30)
Apr 18 05:56:26 PM  == Compilation error in file lib/components_guide/rustler/math.ex ==
Apr 18 05:56:26 PM  ** (RuntimeError) calling `cargo metadata` failed.
Apr 18 05:56:26 PM      (rustler 0.25.0) lib/rustler/compiler/config.ex:87: Rustler.Compiler.Config.metadata!/1
Apr 18 05:56:26 PM      (rustler 0.25.0) lib/rustler/compiler/config.ex:69: Rustler.Compiler.Config.build/1
Apr 18 05:56:26 PM      (rustler 0.25.0) lib/rustler/compiler.ex:9: Rustler.Compiler.compile_crate/2
Apr 18 05:56:26 PM      lib/components_guide/rustler/math.ex:2: (module)
```

I’ve tried setting the `RUSTUP_HOME` and `CARGO_HOME` environment variables to a local `tmp` directory but it still tried to write outside of these.

I have a thread open on the Render community too: https://community.render.com/t/i-need-a-temporary-directory-for-rustler-elixir-to-write-to/3987

For now, I’m using Rustler in development and Rustler Precompiled in production. You can see the file here (my project is open source): https://github.com/ComponentsGuide/components_guide/blob/master/lib/components_guide/rustler/math.ex

**Comment by filmor** [comment]
This is not really a Rustler issue, from what I can see. The call that is failing here is `cargo metadata`, which would fail for a pure Rust project just as well. How did you install Rust in the first place?

**Comment by guidomb** [comment]
I was able to workaround this by setting `CARGO_HOME` env variable in Render.com to `/tmp/.cargo`

**Comment by filmor** [comment]
I guess this is solved with guidomb's suggestion, feel free to reopen if it's not.
