### ISSUE TITLE
Use map_from_arrays() for map construction in rustler_codegen

### ISSUE THREAD

**Issue by evnu** [rusterlium/rustler#451]
As noted in https://github.com/rusterlium/rustler/pull/440, we should try to use `map_from_arrays()` when constructing maps in `rustler_codegen`. As pointed out by @SeokminHong, changing the signature of `map_from_arrays()` to use `impl Encoder` instead of `Term<'a>` could simplify that:

```rust
    pub fn map_from_arrays(
        env: Env<'a>,
        keys: &[impl Encoder],
        values: &[impl Encoder],
    ) -> NifResult<Term<'a>> {
```

**Comment by hansihe** [comment]
As long as we use `impl Encoder + 'a` I believe this should be a non-breaking change?

**Comment by philss** [comment]
Can we use [`map_from_pairs/2`](https://github.com/rusterlium/rustler/blob/de49fa0f43fc9b7af9a33eb3327a593656badbb0/rustler/src/types/map.rs#L58) instead? Anyway, the same change may apply to that function.
