### ISSUE TITLE
Support `enif_make_resource_binary`

### ISSUE THREAD

**Issue by cigrainger** [rusterlium/rustler#452]
This is in [`rustler_sys`](https://docs.rs/rustler_sys/latest/rustler_sys/rustler_sys_api/fn.enif_make_resource_binary.html), but it would be nice to have it wrapped more safely in `rustler`.

I'd be happy to contribute this one but could use some guidance on the API. I was thinking it would make sense to add `ResourceBinary` to `rustler::resource` (though maybe it should live in `rustler::types::binary`?). `ResourceBinary::new` would take a `ResourceArc` and a reference to a binary with a lifetime tied to the resource object. It would hold the cloned `ResourceArc` and the reference to the binary as well as the size of the binary.

Does that sound reasonable? Other than lifetime annotations, are there any other considerations for ensuring the binary data is handled properly if it's external to the resource object?

**Comment by josevalim** [comment]
This can now be closed thanks to #487. :) /cc @filmor

**Comment by filmor** [comment]
Fixed in #487, you can now use `resource_arc.make_binary(|inner| &inner.some_binary)` to create a resource binary.
