### ISSUE TITLE
Mac M1 Architecture compilation issue

### ISSUE THREAD

**Issue by JulesGuesnon** [rusterlium/rustler#459]
Hello! I'm using a [library](https://github.com/tzumby/ex_keccak) that is a NIF under the hood, and I opened [an issue](https://github.com/tzumby/ex_keccak/issues/27) because I had a compilation target issue. 

Then I tried to make a NIF from scratch just to make sure the problem wasn't rustler, and I actually got the same error: 

```
[warning] The on_load function for module Elixir.HelloNif returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen(/Users/julesguesnon/Dev/hello_nif/_build/dev/lib/hello_nif/priv/native/libhellonif.so, 0x0002): tried: \'/Users/julesguesnon/Dev/hello_nif/_build/dev/lib/hello_nif/priv/native/libhellonif.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64e\')), \'/usr/local/lib/libhellonif.so\' (no such file), \'/usr/lib/libhellonif.so\' (no such file), \'/Users/julesguesnon/Dev/hello_nif/priv/native/libhellonif.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64e\')), \'/usr/local/lib/libhellonif.so\' (no such file), \'/usr/lib/libhellonif.so\' (no such file)\''}}
```

The most interesting part being: `mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64e\')`

I don't really get what's happening tho as it seems to already be handled

**Comment by joshuataylor** [comment]
I'm working on Macbook Air M1 fine with Rustler, you're not running on a x86 terminal or whatever it is, right? You can run the terminal through Rosetta, which forces everything to run as x86 instead of ARM64.

Ensure you've also added the following to .cargo/config:
```
[target.'cfg(target_os = "macos")']
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup"
]
```

**Comment by JulesGuesnon** [comment]
Hey @joshuataylor !

Thanks for your answer, I do have the right config, and I have Rosetta installed, so I'll try to see if my terminal is launched through Rosetta. 
But shouldn't rust be able to compile to arm, like, is there a limitation that makes it necessary to run it through Rosetta?

**Comment by filmor** [comment]
The point is, apparently your Rust toolchain is an x86_64 one (installed through Rosetta maybe?), so the binaries it produces are incompatible to your Erlang installation. These two have to match.

**Comment by JulesGuesnon** [comment]
@filmor You were right, I updated my toolchain to `stable-aarch64-apple-darwin` and it worked. Thanks a lot everyone for the help!
