### ISSUE TITLE
NifStruct to built-in Elixir structs

### ISSUE THREAD

**Issue by joshuataylor** [rusterlium/rustler#460]
Hi,

I am writing a deserialiser and I want to be able to do something like this:
```elixir
#[derive(NifStruct)]
#[module = "Date"]
pub struct ElixirDate
{
    pub year: i32,
    pub month: u32,
    pub day: u32
}
```

I am getting the following error back:

```
              %Inspect.Error{message: "got FunctionClauseError with message \"no function clause matching in Inspect.Date.inspect/2\" while inspecting %{__struct__: Date, day: 26, month: 5, year: 2024}"},
```

iex shows the following for the sigil:
```
iex(6)> IO.inspect(~D[2020-01-01], structs: false)
%{__struct__: Date, calendar: Calendar.ISO, day: 1, month: 1, year: 2020}
~D[2020-01-01]
```

And when trying to build an invalid date, shows that the year/month/day are required:
```
iex(7)> IO.inspect(%Date{year: 2020}, structs: false)
** (ArgumentError) the following keys must also be given when building struct Date: [:month, :day]
    (elixir 1.13.4) expanding struct: Date.__struct__/1
```

**Comment by evnu** [comment]
Note that your `NifStruct` must encode every field which is also present in the corresponding Elixir struct, so you probably also need the `calendar` field. I can reproduce the `FunctionClauseError` in `iex`:

```
iex(6)> inspect(%{__struct__: Date, month: 1, day: 1, year: 2020})
"%Inspect.Error{message: \"got FunctionClauseError with message \\\"no function clause matching in Inspect.Date.inspect/2\\\" while inspecting %{__struct__: Date, day: 1, month: 1, year: 2020}\"}"
```

So, you will need to add the `:calendar` field. I think you should be able to use the `Atom` type, and use the `rustler::atoms!()` macro to create the atom `Elixir.Calender.ISO`. Then, when creating an `ElixirDate` (ie. with a `new()` function), you can set the `:calendar` to that constant.

**Comment by joshuataylor** [comment]
That makes sense, thanks. I'll see if I can improve the documentation around this.

**Comment by filmor** [comment]
I'm not sure what the stability guarantees on `struct` fields are in Elixir, but it might make sense to just return a 3-tuple and do `Date.new` on that, functions are more likely to be stable.
