### ISSUE TITLE
Using redpbf Loader causes linker error

### ISSUE THREAD

**Issue by cdegroot** [rusterlium/rustler#484]
I want to call BPF functions through Rust, but as soon as I have an invocation of its loader class in my code, I get an error:

```
  = note: /usr/bin/ld: /vagrant/tmp/rs_test/_build/dev/lib/rs_test/native/rstest/debug/deps/libbpf_sys-9689b15254925376.rlib(libbpf.o): warning: relocation against `stderr@@GLIBC_2.2.5' in read-only section `.text'
          /usr/bin/ld: /vagrant/tmp/rs_test/_build/dev/lib/rs_test/native/rstest/debug/deps/libbpf_sys-9689b15254925376.rlib(libbpf.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
          /usr/bin/ld: final link failed: bad value
          collect2: error: ld returned 1 exit status      
```

I have no clue how this happens or how to make it go away, and while I dig some more, I hope someone can shed a light on this and indicate whether this is a Rustler issue or something funny with the libraries that RedBPF depends on. 

(in the meantime, I guess I'll work around by making the code a Port program, which is not as nice but should work for now).

Steps to reproduce:
* Checkout https://github.com/cdegroot/rustler_issue_484
* `mix compile`

Tested on Ubuntu 22.04 with Rust 1.56.1 (not the latest version, I know, it's tricky to get a BPF+Rust+Rusterl toolchain with all matching versions and this one worked. I don't think it is highly Rust-version sensitive though).

**Comment by evnu** [comment]
@cdegroot is this still relevant? The repository you linked seems to have been deleted. I suspect that the dependency was complied as a `rlib` and missing `-fPIC`, maybe that causes the linker problem.
