### ISSUE TITLE
1.65.0 Clippy complaining in `NifStruct` derives.

### ISSUE THREAD

**Issue by jerzywilczek** [rusterlium/rustler#498]
When using `#[derive(NifStruct)]` on rust 1.65.0, clippy reports "needless borrows" on all fields of the struct. I believe this is caused by the derived `Encoder` impl. I also noticed that rustler does not add the `#[automatically_derived]` attribute on the modules and impls derived automatically. It is possible that adding this attribute could solve this problem.

**Comment by evnu** [comment]
Thanks for the report! I started working on it in #499. Alas, adding `automatically_derived` does not seem to suffice (or I need to apply it somewhere else as well).

**Comment by evnu** [comment]
I allowed `clippy::needless_borrow` for the generated functions in #499. That should fix this.
