### ISSUE TITLE
nif_panicked does not show the panic message

### ISSUE THREAD

**Issue by ishitatsuyuki** [rusterlium/rustler#504]
It looks like a unwind handler was added in #264, but it ends up discarding the error object containing the panic message:
https://github.com/rusterlium/rustler/blob/41a85bc110d9a5a85e11624849302c74debdb471/rustler/src/codegen_runtime.rs#L126

As a result, the panic message is not shown to the user, making it confusing and annoying to debug.

```
    ** (EXIT) an exception was raised:
        ** (ErlangError) Erlang error: :nif_panicked
            (myproject 0.1.0) MyProject.ProcessorNative.parse()
            ...
```

A workaround is to set `panic = 'abort'` in Cargo profile, however this is rather ugly.

**Comment by evnu** [comment]
In `RustlerTest.ThreadTest`, the test `thread panic` triggers a panic. That test has additional output from the panic:

```
thread '<unnamed>' panicked at 'threaded_fac: integer overflow', rustler_tests/native/rustler_test/src/test_thread.rs:11:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I wonder why that is different.

**Comment by ishitatsuyuki** [comment]
Ah, I tested again and it seems it does give the message. When I encountered this it was https://github.com/rusterlium/rustler/issues/72 however, which effectively borked stderr.

Sorry for the noise.
