### ISSUE TITLE
NIF code trying to using MongoDB sync client hangs while trying to connect to DB

### ISSUE THREAD

**Issue by narup** [rusterlium/rustler#508]
Can anyone please help me understand why the code below trying to do db connection gets stuck or blocked when I use it in my NIF module? 

let client = mongodb::sync::Client::with_uri_str("mongodb+srv://p

the same function works outside of rustler project. Couldn't figure out if there's any limitation that I am not aware of 

Thanks

**Comment by narup** [comment]
Looks like it's related to this https://www.erlang.org/doc/man/erl_nif.html#lengthy_work

**Comment by evnu** [comment]
Also note this warning from the [documentation](https://www.erlang.org/doc/man/erl_nif.html):

> A native function is executed as a direct extension of the native code of the VM. Execution is not made in a safe environment. The VM cannot provide the same services as provided when executing Erlang code, such as pre-emptive scheduling or memory protection. If the native function does not behave well, the whole VM will misbehave.

While rustler provides safety w.r.t. memory and data races, special care is still needed when using NIFs. For lengthy work, other schedulers (cpu or io) can be used. But one always needs to ask the question if the work to be done should actually be done with a NIF.

I will close this ticket for now. Feel free to reopen if there is an issue with rustler that should be fixed.
