### ISSUE TITLE
Check if Term is float

### ISSUE THREAD

**Issue by juanazam** [rusterlium/rustler#509]
Hello!

First of all, wanted to say this project is amazing, I'm a newbie at Rust and I was still able to write a nif and use it in Elixir!

While most of what I was set to code is working, there is one more thing I couldn't crack.

The nif I'm working on receives an Elixir map as an argument. The map can have different kinds of values (maps, lists, booleans, ints, floats, etc).

While decoding the Map as a Rust Struct, I'm having issues while decoding numbers. Since the map is dynamic, I don't know beforehand if the value I'm going to decode is an int or a float, and I haven't been able to make this work for both ints and floats at the same time.

This is the code I have:

```
if term.is_number() {
   let number_scalar: f64 = term.decode::<f64>().unwrap();
   ...
}
...
```

In order to call the right decoder, I need to specify the type but given I don't know the type, I can't do that.
I checked rustler and there is no `term.is_float` or `term.is_int` which could help me out.

I imagine the possibility of doing something like:

```
if term.is_int() {
   let number_scalar: i32 = term.decode::<i32>().unwrap();
   ...
} else if term.is_float() {
  let number_scalar: f64 = term.decode::<f64>().unwrap();
}
```

Is this possible? if it's not, does anybody has any recommendations on how to handle this case?

**Comment by filmor** [comment]
- You should not use `unwrap` in "production" code. It will not crash your code but only because Rustler explicitly handles `panic`s
- Instead, you can use `if let` or `match` (or `unwrap_or`, there are plenty of options) to first try to decode as integer and, if that fails, decode as float instead
- @all: Is there any particular reason, why `Term::get_type()` is implemented using the various `is_*` methods (which map to `enif_is_*`)? Erlang's built in `enif_term_type` can actually distinguish floats and integers, changing the behaviour of `get_type` in this way now would be a breaking change, though.

**Comment by juanazam** [comment]
@filmor Thanks so much for your reply! will implement this update!

**Comment by evnu** [comment]
> Is there any particular reason, why Term::get_type() is implemented using the various is_* methods 

[enif_term_type](https://www.erlang.org/doc/man/erl_nif.html#enif_term_type) was introduced with OTP 22.0, so it was  not around when `get_type()` was implemented.

**Comment by filmor** [comment]
Then I'll add it. @rusterlium/core do you think it's fine to break API here by adjusting the enum or should I add a new function?

**Comment by evnu** [comment]
> https://github.com/orgs/rusterlium/teams/core do you think it's fine to break API here by adjusting the enum or should I add a new function?

I'd tend to deprecate this function and schedule for removal in 1.0, and add a new function instead.

Maybe `impl From<Term> for TermType` would be the way to go here. That allows us to keep the deprecated function around and avoid thinking of a new name. Alternatively, `Term::as_type` should fit as well, as this is a cheap function.

> I imagine the possibility of doing something like:

Note that you can also try to decode and handle the error:

```rust
enum MyType {
  Float(f64),
  Integer(i64)
}

fn decode_the_term(term: Term)  -> MyType {
  if let Ok(float) = term.decode::<f64>() { return MyType::Float(float); }
  if let Ok(integer) = term.decode::<f64>() { return MyType::Integer(integer); }
  panic!("This should probably never happen.");
}
```

`rustler_codegen` can help you here by deriving that decoder above automatically. `NifUntaggedEnum` implements `Decode` and `Encode` for an `enum`. Example:

```rust
#[derive(NifUntaggedEnum)]
enum MyEnum {
  Float(f64),
  Integer(i64)
}

#[rustler::nif]
fn my_nif(my_enum: MyEnum) -> MyEnum {
  my_enum // this is a variant of MyEnum, which was already decoded and which will be encoded after it was returned
}
```

(Disclaimer: I did not compile the code above :))
