### ISSUE TITLE
`nif` macro fails with macro arguments

### ISSUE THREAD

**Issue by denumerate** [rusterlium/rustler#519]
The `nif` macro fails when a tuple is passed to a function, like below:
```
#[rustler::nif]
fn test_fn(item: (usize, usize)) -> (usize, usize) {
    (item.0 + 1, item.1 + 1)
}
```

The error is:
```
error: custom attribute panicked
  --> src/lib.rs:37:1
   |
37 | #[rustler::nif]
   | ^^^^^^^^^^^^^^^
   |
   = help: message: unsupported input given: Tuple(TypeTuple { paren_token: Paren, elems: [Path(TypePath { qself: None, path: Path { leading_colon: None, segments: [PathSegment { ident: Ident { ident: "usize", span: #0 bytes(1029..1034) }, arguments: None }] } }), Comma, Path(TypePath { qself: None, path: Path { leading_colon: None, segments: [PathSegment { ident: Ident { ident: "usize", span: #0 bytes(1036..1041) }, arguments: None }] } })] })
```

I looked into rustler_codegen and it looks like tuple isn't supported in the macro. Is there any special reason for this? Tuples are types provided by the standard library in both rust and elixir, and already have both decode and encode implemented. I could use the `NifTuple` macro, but I'd probably just be re-implementing tuples, which seems wasteful.

**Comment by filmor** [comment]
It should be enough to add a `syn::Type::Tuple` branch to this `match` https://github.com/rusterlium/rustler/blob/master/rustler_codegen/src/nif.rs#L118

The dexoder already exists, so you can probably just use the exact same implementation as https://github.com/rusterlium/rustler/blob/master/rustler_codegen/src/nif.rs#L119-L128

**Comment by denumerate** [comment]
Thanks for the help! That at least worked locally
