### ISSUE TITLE
Expose `enif_is_process_alive`

### ISSUE THREAD

**Issue by zachallaun** [rusterlium/rustler#540]
Happy to take a shot at adding this if there are no objections. 

Edit: just saw #44, where both this and enif_is_current_process_alive are mentioned.

**Comment by filmor** [comment]
The function is already in `rustler_sys`, you just need to add a function on `Env` in the `local_pid` module (like the existing `pid()` function there).

**Comment by zachallaun** [comment]
Want to make sure I understand the project structure correctly — would you implement `is_process_alive` and `is_current_process_alive` [here](https://github.com/rusterlium/rustler/blob/master/rustler/src/wrapper/pid.rs#L12) that operate on the underlying types, and then create the public interface that uses those wrappers [here](https://github.com/rusterlium/rustler/blob/d8aa66d976fa5ebbc6f74662992448a79a7d2fbf/rustler/src/types/local_pid.rs#L34)?

**Comment by filmor** [comment]
Sorry for the late reply. I think I'd like all of these, where of course `pid.is_process_alive` could just redirect to the implementation on `env`.

**Comment by filmor** [comment]
Implemented in #599, will be in the next release.
