### ISSUE TITLE
This OTP release uses the unsupported Erlang NIF version "2.17"

### ISSUE THREAD

**Issue by rk108** [rusterlium/rustler#557]
Hi!

Erlang/OTP 26, erts-14.0.1 throw error while compiling:

This OTP release uses the unsupported Erlang NIF version "2.17".

FullMsg:
`error: failed to run custom build command for `rustler_sys v2.0.0`

Caused by:
  process didn't exit successfully: `/home/.../_build/default/lib/erbloom/crates/bloom/target/release/build/rustler_sys-61c7907ec020bc63/build-script-build` (exit status: 101)
  --- stdout
  This OTP release uses the unsupported Erlang NIF version "2.17".

  Please report at https://github.com/rustlerium/rustler.

  --- stderr
  thread 'main' panicked at 'gen_api.erl encountered an error.', /home/iero/.cargo/registry/src/index.crates.io-
6f17d22bba15001f/rustler_sys-2.0.0/build.rs:34:18

````

**Comment by filmor** [comment]
[`erlbloom`](https://github.com/Vonmo/erbloom) uses an old version of Rustler that didn't have support for OTP26, yet. You'll need to ask the project to update (or update it yourself) and it will work again.
