### ISSUE TITLE
[Feature request] Add support for i128 and u128

### ISSUE THREAD

**Issue by Munksgaard** [rusterlium/rustler#594]
Since both Rust and Elixir have support for 128-bit sized integers ([i128](https://doc.rust-lang.org/std/primitive.i128.html), [u128](https://doc.rust-lang.org/std/primitive.u128.html), [erlang](https://www.erlang.org/doc/efficiency_guide/advanced#memory)) it seems natural that Rustler should support it as well.

I have a specific use case for i128s as well, which is implementing support for the [Decimal](https://docs.rs/polars/latest/polars/datatypes/enum.AnyValue.html#variant.Decimal) type from Polars in [Explorer](https://github.com/elixir-explorer/explorer/issues/867).

**Comment by Munksgaard** [comment]
I can't really figure out if [this](https://github.com/rust-lang/rust/issues/54341) is going to be a problem, but at least it's something to be aware of.

**Comment by evnu** [comment]
Would this work for you: https://github.com/rusterlium/rustler/tree/master/rustler_bigint ?

**Comment by filmor** [comment]
> I can't really figure out if [this](https://github.com/rust-lang/rust/issues/54341) is going to be a problem, but at least it's something to be aware of.

I don't think this is relevant for Rustler. It would be, if the NIF API actually included (C-based) support for 128-bit integer types, but it only supports up to 64.

If someone wants to work on this, https://github.com/rusterlium/rustler/tree/master/rustler_bigint can be taken as a basis. While that library is more general and implements support for arbitrarily-sized integers, the same approach (going via the `term_to_binary`) can be used for the standard library types `i128` and `u128`.

**Comment by Munksgaard** [comment]
I have not had time to look at the bigint library yet, but it indeed seems like the easiest way to handle something like this.

**Comment by Munksgaard** [comment]
Incredible! Thank you for your work @filmor!
