### ISSUE TITLE
[Feature request] Support for serializing Path/PathBuf

### ISSUE THREAD

**Issue by begleynk** [rusterlium/rustler#598]
Would it be possible to implement [Encoder](https://docs.rs/rustler/latest/rustler/types/trait.Encoder.html)/[Decoder](https://docs.rs/rustler/latest/rustler/types/trait.Decoder.html) for Rust's [Path](https://doc.rust-lang.org/std/path/struct.Path.html)/[Pathbuf](https://doc.rust-lang.org/std/path/struct.PathBuf.html) types?

I'm currently working on a project where I own all the types in a complex struct, but because the standard library's Path/PathBuf can't be serialized over to Elixir, it's forcing me to create wrapper types. This would be a huge ergonomic benefit.

Happy to contribute a PR if this is straightforward.

Thanks for all your work on Rustler ❤️

**Comment by filmor** [comment]
If all you are looking for is `Path(Buf) <-> binary string`, I don't see a problem with that.

**Comment by begleynk** [comment]
Yup that's fine by me 👍 The Elixir [`Path`](https://hexdocs.pm/elixir/1.13/Path.html) module just works on binary strings, so this seems reasonable.

I'll try to contribute a PR for this in the coming days/weeks.
