### ISSUE TITLE
Missing `priv` library does not trigger re-compile

### ISSUE THREAD

**Issue by ggwpez** [rusterlium/rustler#616]
Hey thanks for the project, really useful 😄

When I delete the `.so` files in the `priv/native/` folder, then the following `mix test` invocation will error that they are not found:

```pre
error: module ErasureCoding.Native is not loaded and could not be found
    │
  3 │   doctest ErasureCoding.Native
    │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │
    └─ test/bindings/erasure_coding_test.exs:3: Bindings.ErasureCoding.Test (module)


20:57:18.167 [warning] The on_load function for module Elixir.ErasureCoding.Native returned:
{:error,
 {:load_failed,
  ~c"Failed to load NIF library: 'dlopen(... 'graymatter/priv/native/liberasure_coding.so' (no such file)'"}}
```

I got around this by adding:

```elixir
@external_resource "priv/native/liberasure_coding.so"
```

To my NIF module [here](https://github.com/JamBrains/graymatter/blob/6d79e7d5c9318e8f455e334528ad82da62cff6a4/lib/bindings/erasure_coding.ex#L8). Is this expected or could maybe Rustler already generate this attribute in its derive macro?  

Having it auto recompile in these cases helps when Ctrl-C-ing the build or in CI where caching does not restore everything. 
Hopefully this is easy to reproduce, otherwise I will make an example project.

```pre
{:rustler, "~> 0.33.0"},
$ elixir -v
Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.16.3 (compiled with Erlang/OTP 26)

on MacOS 14.5

**Comment by filmor** [comment]
The issue is simply that we currently don't count the copied build artifacts themselves as "external resources". It's not hard to fix this.
