### ISSUE TITLE
Rustler version not found "0.33.1"

### ISSUE THREAD

**Issue by samfrench** [rusterlium/rustler#622]
Should this be version "0.33.0"?
> https://github.com/rusterlium/rustler/blob/master/rustler_mix/lib/rustler.ex#L173

Otherwise I get an error when trying to start in iex.
```
Compiling 1 file (.ex)
    Updating crates.io index
error: failed to select a version for the requirement `rustler = "^0.33.1"`
candidate versions found which didn't match: 0.33.0, 0.32.1, 0.31.0, ...
location searched: crates.io index
```

**Comment by filmor** [comment]
Oh, I'm sorry, I must have made a fat-finger mistake on the last release. The only place where this matters is when you first create a new Rustler project. You can adjust the generated `Cargo.toml` accordingly.

**Comment by samfrench** [comment]
Hi @filmor, I did change the line in the Cargo.toml and then it worked. Was asking in case it needed changing but wasn't sure if it was meant to be the newer version number. Thank you for replying.

**Comment by filmor** [comment]
Fixed (and improved the behaviour) with the release of 0.34.0.
