### ISSUE TITLE
Panics in return value encoding crash the VM

### ISSUE THREAD

**Issue by ethanwu10** [rusterlium/rustler#655]
If the implementation of `rustler::Encoder::encode` panics during encoding of a return value from a `#[rustler::nif]` method, the panic is not caught and brings down the whole VM.

In the implementation of the `nif` macro, return value conversion is handled outside of the `catch_unwind` block:
https://github.com/rusterlium/rustler/blob/566cc7ca8be1b2cbda1b6be22f1ccc45ade5a279/rustler_codegen/src/nif.rs#L83-L91
While this is necessary to convert a caught panic from within the NIF function itself (which is rustler code and thus can be assumed to not panic), this also puts encoding for normal return values with library-user-controlled `Encoder` implementations outside the `catch_unwind`.

As an example, I happened to run into this when using a malformed `SerdeTerm` as a return value; the serde code panicked and brought down the VM.

**Comment by filmor** [comment]
You are right, this is an oversight.
