### ISSUE TITLE
rust target beint init as macos althought it's been generated on linux

### ISSUE THREAD

**Issue by henriquesati** [rusterlium/rustler#673]
i'm running rustler on a ubuntu 22.02 distro on WSL2 and when I gen the nifs, .cargo/config.toml is setting the target as macos, is this on purpose?
config.toml
```
[target.'cfg(target_os = "macos")']
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]
```
dir structure
native
        --solana
              --.cargo
               config.toml
              --src
              cargo.toml

**Comment by filmor** [comment]
That is not what this file does. The first line ensures that the given linker settings are *only* applied *if* your target is `macos`.
